### ISSUE TITLE
Broke on Windows 8.1

### ISSUE THREAD

**Issue by sebwojtasik** [andr3wmac/Torque6#26]
I compiled the engine on my Windows 8.1 machine with Visual Studio 2015, but it's not working. It only works for the console demo, otherwise displays black screen and the output is stuck at:
`Asking to load DDS!`
Tried compiling under 64 a 32 bit architecture. I also tried using Visual Studio 2013 but it gives the same results. Using Direct3D 11 renderer.

**Comment by andr3wmac** [comment]
Whats system specs? Can you post console.log from AnimatedMesh example? Thanks.

**Comment by sebwojtasik** [comment]
I'm on 64-bit Windows 8.1 with Intel i5, Nvidia GeForce 410M and 6 Gb RAM. And I'll post the log in a second.

**Comment by TheWilfen** [comment]
Here's the console.log
'//-------------------------- 2/15/2016 -- 20:48:58 -----
Console trace is off.
Adding path expando of 'AppCore' as 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/AppCore/1'.
Asset Manager: Failed to scan declared assets in directory 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/AppCore/1/assets'.
AssetManager::addModuleDeclaredAssets() - Could not scan for declared assets at location 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/AppCore/1/assets' with extension 'asset.taml'.
--------------------------------------------------------------------------------
Video initialization:
   Activating the BGFX display device...
BGFXDevice::setScreenMode -- can't switch to resolution larger than desktop in windowed mode!
   Setting screen mode to 1024x768x32 (w)...
   Creating a new window...
   Acquiring a new device context...

--------------------------------------------------------------------------------
Available Renderers:
   Direct3D 9
   Direct3D 11
   Direct3D 12
   OpenGL 2.1
Current Renderer: Direct3D 11
BGFXDevice::setScreenMode -- can't switch to resolution larger than desktop in windowed mode!
OpenAL Driver Init
OpenALInitDriver() failed
Adding path expando of 'Console' as 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/Console/1'.
Warning: (..\..\src\io\resource\resourceManager.cc @ 883) ResourceObject::construct: NULL resource create function.
ResourceObject::construct: NULL resource create function for 'lucida console.ttf'.
@@@ Console::create function called
Adding path expando of 'NetworkCore' as 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/NetworkCore'.
Binding server port to default IP
UDP initialized on port 0
Adding path expando of 'Sky' as 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/Sky/1'.
Adding path expando of 'ExampleRoom' as 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/ExampleRoom/1'.
Adding path expando of 'AnimatedMeshExample' as 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/modules/AnimatedMeshExample/1'.
Importing mesh..
Generating material vertex shader..
Generating material pixel shader..
Generating material skinned vertex shader..
Generating texture mip maps..
Asset Manager: Failed to acquire asset Id 'AnimatedMeshExample:T6PrototypeNormalMap' as it does not exist.
MaterialAsset : Failed to load texture asset.
Generating texture mip maps..
Asset Manager: Failed to acquire asset Id 'AnimatedMeshExample:T6PrototypeRoughnessMap' as it does not exist.
MaterialAsset : Failed to load texture asset.
Asset Manager: Failed to acquire asset Id 'AnimatedMeshExample:T6PrototypeMetallicMap' as it does not exist.
MaterialAsset : Failed to load texture asset.'

**Comment by sebwojtasik** [comment]
Here's the log

```
//-------------------------- 2/15/2016 -- 20:07:31 -----
Console trace is off.
Asset Manager: Failed to scan declared assets in directory 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/AppCore/1/assets'.
AssetManager::addModuleDeclaredAssets() - Could not scan for declared assets at location 'C:/Users/Sebastian/Desktop/Torque6/projects/01-AnimatedMesh/../shared-modules/AppCore/1/assets' with extension 'asset.taml'.
--------------------------------------------------------------------------------
Video initialization:
   Activating the BGFX display device...
BGFXDevice::setScreenMode -- can't switch to resolution larger than desktop in windowed mode!
   Setting screen mode to 1024x768x32 (w)...
   Creating a new window...
   Acquiring a new device context...

--------------------------------------------------------------------------------
Available Renderers:
   Direct3D 9
   Direct3D 11
   Direct3D 12
   OpenGL 2.1
Current Renderer: Direct3D 11
BGFXDevice::setScreenMode -- can't switch to resolution larger than desktop in windowed mode!
OpenAL Driver Init
OpenALInitDriver() failed
ResourceObject::construct: NULL resource create function for 'lucida console.ttf'.
@@@ Console::create function called
Binding server port to default IP
UDP initialized on port 0
Importing mesh..
Asset Manager: Failed to acquire asset Id 'AnimatedMeshExample:T6PrototypeNormalMap' as it does not exist.
MaterialAsset : Failed to load texture asset.
Asset Manager: Failed to acquire asset Id 'AnimatedMeshExample:T6PrototypeRoughnessMap' as it does not exist.
MaterialAsset : Failed to load texture asset.
Asset Manager: Failed to acquire asset Id 'AnimatedMeshExample:T6PrototypeMetallicMap' as it does not exist.
MaterialAsset : Failed to load texture asset.
```

**Comment by andr3wmac** [comment]
Might be this:

```
BGFXDevice::setScreenMode -- can't switch to resolution larger than desktop in windowed mode!
```

What is your desktop resolution?

**Comment by sebwojtasik** [comment]
1366 x 768

**Comment by andr3wmac** [comment]
Default window resolution is 1024x768 and I currently don't have anything in place to determine a fallback resolution when the window is larger than the available desktop space. I will fix this soon. In the mean time you can change the default window resolution here:

https://github.com/andr3wmac/Torque6/blob/master/projects/shared-modules/AppCore/1/scripts/defaultPreferences.tsc#L66-L67

**Comment by sebwojtasik** [comment]
Well it made a partial fix for two of projects (materials and terrain it starts but it doesn't render properly), still blackscreen on AnimatedMesh.

**Comment by sebwojtasik** [comment]
![materials](https://cloud.githubusercontent.com/assets/1448623/13059748/affdac22-d42c-11e5-83ba-ad7820990f33.png)

**Comment by andr3wmac** [comment]
That's actually what it looks like on mine too. I'm still fixing things after a recent rendering refactor. That issue is next on my list :) I often push partially complete features. I should probably make better use of branches haha.

**Comment by sebwojtasik** [comment]
I thought it was just my build haha. I guess I'll check out the older build then, maybe other projects will work then too. Anyway thank you for really fast help :smiley:

**Comment by andr3wmac** [comment]
@TheWilfen Pull the latest and the material example should be fixed. Rendering refactor is pretty much complete at this point. I'll go through the rest of the examples tomorrow and fix whatever is broken.

**Comment by sebwojtasik** [comment]
Well it didn't help at all, I guess it made it even worse as now it crashes my graphics card driver. (it launched once but gave same buggy results as before). Ugh :disappointed:

**Comment by andr3wmac** [comment]
Interesting. Could you regenerate the visual studio project from the build folder, then do a clean rebuild of the project just to be sure? If you get the same results from the material example can you post the console.log? I suspect it's the cubemap convolution that's crashing your graphics driver but those shaders haven't changed so I can't think of why it would be crashing all of a sudden.

**Comment by sebwojtasik** [comment]
Still the same. Here's the log:

```
//-------------------------- 2/16/2016 -- 16:24:51 -----
Console trace is off.
Adding path expando of 'AppCore' as 'C:/Users/Sebastian/Desktop/Torque6-master/projects/06-Materials/../shared-modules/AppCore/1'.
Asset Manager: Failed to scan declared assets in directory 'C:/Users/Sebastian/Desktop/Torque6-master/projects/06-Materials/../shared-modules/AppCore/1/assets'.
AssetManager::addModuleDeclaredAssets() - Could not scan for declared assets at location 'C:/Users/Sebastian/Desktop/Torque6-master/projects/06-Materials/../shared-modules/AppCore/1/assets' with extension 'asset.taml'.
--------------------------------------------------------------------------------
Video initialization:
   Activating the BGFX display device...
   Setting screen mode to 500x500x32 (w)...
   Creating a new window...
   Acquiring a new device context...

--------------------------------------------------------------------------------
Available Renderers:
   Direct3D 9
   Direct3D 11
   Direct3D 12
   OpenGL 2.1
Current Renderer: Direct3D 11
OpenAL Driver Init
OpenALInitDriver() failed
Adding path expando of 'Console' as 'C:/Users/Sebastian/Desktop/Torque6-master/projects/06-Materials/../shared-modules/Console/1'.
Warning: (c:\users\sebastian\desktop\torque6-master\src\io\resource\resourcemanager.cc @ 883) ResourceObject::construct: NULL resource create function.
ResourceObject::construct: NULL resource create function for 'lucida console.ttf'.
@@@ Console::create function called
Adding path expando of 'Sky' as 'C:/Users/Sebastian/Desktop/Torque6-master/projects/06-Materials/../shared-modules/Sky/1'.
Adding path expando of 'ExampleCamera' as 'C:/Users/Sebastian/Desktop/Torque6-master/projects/06-Materials/../shared-modules/ExampleCamera/1'.
Asking to load DDS!
Adding path expando of 'ExampleRoom' as 'C:/Users/Sebastian/Desktop/Torque6-master/projects/06-Materials/../shared-modules/ExampleRoom/1'.
```

**Comment by andr3wmac** [comment]
Hmm. Okay can you go into this file and remove these two lines and run it again:
https://github.com/andr3wmac/Torque6/blob/master/projects/shared-modules/ExampleCamera/1/exampleCamera.scene.taml#L21-L22

The PBR in the materials won't look right but this will disable cubemap convolution and give me an idea if thats the source of the problem. Thanks.

**Comment by sebwojtasik** [comment]
Yeah, that was the issue. It works now.

**Comment by andr3wmac** [comment]
Okay, I know what's causing it. The cubemap convolution shader is taking too long to execute on your mobile GPU and your OS/Driver is killing execution because it thinks its stalled. I have a few ways I can get around this. I'll likely have something for you to try later this evening.

**Comment by sebwojtasik** [comment]
I'm counting days till I'll be able to afford a better workstation haha. Thanks anyway :smile:

**Comment by andr3wmac** [comment]
Well, it's good that this happened otherwise I would have continued with the shader in its current form. Even if its slow I want the environment mapping to be able to be executed even on limited platforms without a crash. Thanks for taking the time to try the engine out, it really helps getting bug reports like this.

**Comment by andr3wmac** [comment]
@TheWilfen Can you pull the latest, put back the skylight, and try the material example again? I've changed the radiance map generation to render in a tiled fashion that should _hopefully_ prevent the timeout. Let me know if it works.

**Comment by sebwojtasik** [comment]
Yeah it works now! Terrain plugin doesn't compile now tho but I'm not able to check it out at the moment. But really big thanks for fixing the PBR. Awesome work you do :+1:

**Comment by andr3wmac** [comment]
That's great news! I refactored Terrain a bit in a step towards fixing it and ended up removing 2 files and added 3 more so if you didn't regenerate the visual studio project those files are likely missing, causing it to not compile. I'm going to fix up the rest of Terrain this evening, on my end it renders but the texture is missing.

I'm going to leave this issue open until I fix your original resolution issue (I'll try to take a look at it tonight as well). Hopefully you don't mind testing the fix for that when I put it in :)

**Comment by sebwojtasik** [comment]
Yeah I discovered I needed to delete terrain.cpp file as I still haven't bothered to properly use Git on Windows haha. And I feel honored to test your engine as I really like concepts behind it that match my ideas alot (I was actually trying to implement similar GI technique as you, hybrid of LPV and VXGI but i gave up as I found it too heavy to handle myself as I don't have much free time right now :p).
